# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9c0b20bc87544a16c92eaa0241dcba37721f2c968ca31178747eea5c0560433898209f636c678399bccc8b7b5f31bccdc5ea698ba10e15e5fa2997a9c0e144c

test:
  secret_key_base: 2873c0fe3548ab74f2657aaef7985cea7198fd756c4c578a0ce9941471cdb828f4c1c3eb492756c1ce468d68bce5a1adbe64ef7a8760f1db487e7a7f2f18cced

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
